export const Images = {
  bg_logo: require('../assets/images/screen.png'),
  bg_circle: require('../assets/images/bg_circle.png'),
  bg_sheep: require('../assets/images/bg_sheep.png'),

  ic_app: require('../assets/images/app_icon.png'),
  ic_birds: require('../assets/images/ic_birds.png'),
  ic_bird: require('../assets/images/ic_bird.png'),
  ic_info: require('../assets/images/ic_info.png'),
  ic_wallet: require('../assets/images/wallet.png'),
  ic_pass: require('../assets/images/ic_pass.png'),
  ic_email: require('../assets/images/ic_email.png'),
  ic_eye: require('../assets/images/ic_eye.png'),
  ic_menu: require('../assets/images/ic_menu.png'),
  ic_users: require('../assets/images/ic_users.png'),
  ic_task: require('../assets/images/ic_task.png'),
  ic_add_circle: require('../assets/images/ic_add_circke.png'),
  ic_add: require('../assets/images/ic_add.png'),
  ic_signout: require('../assets/images/ic_signout.png'),
  ic_coin: require('../assets/images/coin.png'),
  ic_stack: require('../assets/images/stack.png'),
  ic_telegram: require('../assets/images/fa_telegram.png'),
  ic_cart: require('../assets/images/cart.png'),
  ic_tasks: require('../assets/images/task.png'),
};
